sudo: false
language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"

addons:
    apt:
        packages:
            - g++-5
            - libatlas-base-dev
install:
    - pip install --upgrade pip setuptools wheel 
    - pip install --only-binary=numpy,scipy -U ply "networkx>=2" colorlog numpy scipy pytest-xdist pytest pythran
    - pip install .

script:
    - py.test
    
