sudo: false
language: python
dist: xenial
group: travis_latest
python:
    - "3.5"
    - "3.6"
    - "3.7-dev"

addons:
    apt:
        packages:
            - g++-5
            - libatlas-dev
            - libatlas-base-dev
            # Speedup builds
            - eatmydata

cache: pip

install:
    - pip install --upgrade pip setuptools wheel 
    - pip install --only-binary=numpy,scipy -U numpy scipy pytest pythran
    - pip install .

matrix:
    include:
    - name: "3.6 + pythran master"
      python: "3.6"
      install: 
          - pip install --upgrade pip setuptools wheel 
          - pip install --only-binary=numpy,scipy -U numpy scipy pytest
          - pip install git+https://github.com/serge-sans-paille/pythran
          - pip install .
    allow_failures:
    - name: "3.6 + pythran master"

env: OMP_NUM_THREADS=2
script:
    - sh tests/run_tests.sh
 
